---
- name: "Building SRLG Configuration"
  template: src={{ os }}/SRLG.j2 dest={{ baseconfdir.path }}/08_SRLG.out
  changed_when: False
  #when: commit_changes | match('0')
  #when: commit_changes == '0'
  tags:
    - srlg